modLoader="javafml"
loaderVersion="[47,)"
license="MIT"
issueTrackerURL="https://github.com/wiIkwq/FinalProtocol/issues"

[[mods]]
modId="finalprotocol"
version="1.0.0"
displayName="Final Protocol"
updateJSONURL="https://github.com/wiIkwq/FinalProtocol/releases/latest"
displayURL="https://github.com/wiIkwq/FinalProtocol"
logoFile="assets/finalprotocol/logo.png"
credits="wiIk_wq"
authors="wiIk_wq"
description=''' 
An advanced Mekanism addon introducing the Final Protocol Core —
a high-tech failsafe that stores your inventory data upon death.
Energy-driven, risk-balanced, and fully integrated with Mekanism’s
security and energy systems.
'''

[[dependencies.finalprotocol]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.finalprotocol]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"

[[dependencies.finalprotocol]]
modId="mekanism"
mandatory=true
versionRange="[10.4.0,)"
ordering="AFTER"
side="BOTH"